### ISSUE TITLE
[bug]Mathjax公式渲染问题

### ISSUE THREAD

**Issue by dudulumashiro** [blleng/hexo-theme-lx#8]
在更新版本之前，无论是行内公式还是公式块都没有问题。更新后（0.3.8），行内公式渲染失败，有的公式块右侧会出现小箭头。
看了一下博主的引导页，发现博主似乎是把行内公式的写法由$…$变成\\(…\\)了，该项解决。
但是博主的公式块右侧同样出现了小箭头，以前是没有的，推测可能是调整行间距之类的时候有了什么问题，不知道能不能解决。
在此先谢过博主。

**Comment by blleng** [comment]
我已经注意到了这个问题，在下一个版本会解决的。
下一个版本可能要等到七月了。

**Comment by ooyuuhi** [comment]
请问，要怎样才能不使用您默认的从jsdelivr加载css样式和JS文件呢？比如说，我觉得左侧占比太宽了，想要改窄一点。又或者说其他布局我想自定义一些该怎么办？能让它加载git上自己目录下的css和JS吗？实在抱歉提出这个问题，另外谢谢您开发的主题！

Excuse me, I want to know how to load "CSS" and "JS" in the root of "git", Instead of using the// cdn.jsdelivr.net/npm/theme -lx@0.3.9/source/css/ ” this way. Because I want to change some styles. Sorry, can you help me? At last, thank you for developing the theme.

**Comment by blleng** [comment]
> 请问，要怎样才能不使用您默认的从jsdelivr加载css样式和JS文件呢？比如说，我觉得左侧占比太宽了，想要改窄一点。又或者说其他布局我想自定义一些该怎么办？能让它加载git上自己目录下的css和JS吗？实在抱歉提出这个问题，另外谢谢您开发的主题！
> 
> Excuse me, I want to know how to load "CSS" and "JS" in the root of "git", Instead of using the// cdn.jsdelivr.net/npm/theme -lx@0.3.9/source/css/ ” this way. Because I want to change some styles. Sorry, can you help me? At last, thank you for developing the theme.

@Akirako 

主题配置文件最末有开发者选项。
